[build-system]
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = 6.0
required_plugins = ["nbval>=0.10.0"]
testpaths = ["tests", "examples"]
addopts = "--nbval"
