name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  standard:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest]
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        persist-credentials: false

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Build and install
      run: pip install --verbose .

    - name: Test
      run: |
        pip install --upgrade pytest
        pytest
