name: Release

on:
  push:
    tags: ["v*"]

jobs:
  sdist:
    name: Release source distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Build sdist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v3
      with:
        path: dist/*.tar.gz

  wheels:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest]

    name: Release wheels on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: pypa/cibuildwheel@v2.10.0

    - uses: actions/upload-artifact@v3
      with:
        path: wheelhouse/*.whl
